services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Schubwerk\ContaoSchubwerkTrackingBundle\:
    resource: ../../
    exclude: ../../{Entity,Migrations,Model,Resources,Tests,Widget}
  Schubwerk\ContaoSchubwerkTrackingBundle\Controller\ForwardController:
    tags: ['controller.service_arguments']
  Schubwerk\ContaoSchubwerkTrackingBundle\Services\Config:
    public: true
